# Generated by Django 4.0.3 on 2023-02-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminName', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('profile', models.ImageField(upload_to='profilesAdmin/')),
            ],
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('profile', models.ImageField(upload_to='profilesAdmin/')),
            ],
        ),
    ]
